security:
  basic:
      enabled: false

management:
   security:
      enabled: false

logging:
   level:
       io:
           pivotal: DEBUG

spring:
  cloud:
      services:
            registrationMethod: route

spring:
  sleuth:
      sampler:
            percentage: 100.0
